"use client";

export const dynamic = "force-dynamic";
import React from 'react';
import Link from 'next/link';
import { Sparkles, BarChart3, BellRing, FileSearch, ArrowRight } from 'lucide-react';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';

export default function LandingPage() {
  const features = [
    {
      title: 'Real Time Intelligence',
      description: 'Monitor every move your competitors make across the web, from pricing to social sentiment.',
      icon: BarChart3,
    },
    {
      title: 'Instant Alerts',
      description: 'Get notified immediately via app or email whenever a key event triggers a threshold.',
      icon: BellRing,
    },
    {
      title: 'AI Reports',
      description: 'Deep-dive into comprehensive analysis generated by Gemini AI for actionable insights.',
      icon: FileSearch,
    },
  ];

  const handleLogin = () => {
    window.location.href = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000') + '/auth/google';
  };

  return (
    <div className="min-h-screen bg-background text-text-primary selection:bg-accent/30">
      {/* Header */}
      <nav className="max-w-7xl mx-auto px-6 h-24 flex items-center justify-between">
        <div className="text-2xl font-black bg-gradient-primary bg-clip-text text-transparent tracking-tighter">
          Jupid AI
        </div>
        <div className="hidden md:flex gap-8 text-sm font-semibold text-text-secondary">
          <a href="#features" className="hover:text-text-primary transition-colors">Features</a>
          <a href="#" className="hover:text-text-primary transition-colors">How it works</a>
        </div>
        <div className="flex gap-4">
          <Link href="/login">
            <Button variant="ghost">Log in</Button>
          </Link>
          <Button onClick={handleLogin}>Start Analysis</Button>
        </div>
      </nav>

      {/* Hero */}
      <main className="relative max-w-7xl mx-auto px-6 pt-24 pb-40 flex flex-col items-center text-center overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-accent/20 rounded-full blur-[120px] -z-10 opacity-50" />
        
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-surface2 border border-border-custom text-accent rounded-full text-xs font-bold uppercase tracking-widest mb-10 animate-in fade-in slide-in-from-top-4 duration-700">
          <Sparkles size={14} />
          <span>Next-Gen Competitor Intelligence</span>
        </div>
        
        <h1 className="text-6xl md:text-8xl font-black tracking-tight max-w-5xl mb-8 leading-[0.9] animate-in fade-in slide-in-from-top-8 duration-700">
          Know Your Competition.<br />
          <span className="bg-gradient-primary bg-clip-text text-transparent">Stay Ahead Always.</span>
        </h1>
        
        <p className="text-xl text-text-secondary max-w-2xl mb-12 leading-relaxed animate-in fade-in slide-in-from-top-12 duration-1000">
          Jupid AI delivers real-time market signals and Gemini-powered insights, turning raw competitive data into your biggest advantage.
        </p>

        <div className="flex flex-col sm:flex-row gap-4 animate-in fade-in slide-in-from-top-16 duration-1000">
          <Button size="lg" onClick={handleLogin} className="px-10 h-16 text-lg">
            Get Started with Google <ArrowRight className="ml-2" size={20} />
          </Button>
          <Button size="lg" variant="secondary" className="px-10 h-16 text-lg">
            How it works
          </Button>
        </div>

        {/* Features Grid */}
        <div id="features" className="grid md:grid-cols-3 gap-8 mt-48 w-full text-left">
          {features.map((feature, i) => (
            <Card key={i} className="group hover:border-accent transition-all duration-500 hover:-translate-y-2 bg-surface/50 backdrop-blur-sm">
              <div className="w-14 h-14 rounded-2xl bg-surface2 flex items-center justify-center text-accent mb-8 group-hover:scale-110 transition-transform duration-500 border border-border-custom group-hover:border-accent/40">
                <feature.icon size={26} />
              </div>
              <h3 className="text-2xl font-bold mb-4">{feature.title}</h3>
              <p className="text-text-secondary leading-relaxed text-lg">
                {feature.description}
              </p>
            </Card>
          ))}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border-custom py-20 bg-surface/30">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-10">
          <div className="flex flex-col gap-4">
            <div className="text-2xl font-black bg-gradient-primary bg-clip-text text-transparent">Jupid AI</div>
            <p className="text-text-muted text-sm max-w-xs">AI-powered intelligence for the next generation of industry leaders.</p>
          </div>
          
          <div className="flex gap-12 text-sm text-text-muted font-bold tracking-wider uppercase">
            <a href="#" className="hover:text-accent transition-colors">Privacy</a>
            <a href="#" className="hover:text-accent transition-colors">Terms</a>
            <a href="#" className="hover:text-accent transition-colors">Contact</a>
          </div>
          
          <div className="text-sm text-text-muted font-medium">
            © 2025 Jupid AI. Built for champions.
          </div>
        </div>
      </footer>
    </div>
  );
}
