"use client";

import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import api from '@/lib/api';
import { Report } from '@/types';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Badge from '@/components/ui/Badge';
import { SkeletonTable } from '@/components/ui/Skeleton';
import EmptyState from '@/components/ui/EmptyState';
import { FileSearch, Search, Calendar, ChevronRight } from 'lucide-react';
import Link from 'next/link';

export default function ReportsContent() {
  const searchParams = useSearchParams();
  const [reports, setReports] = useState<Report[]>();
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  
  const competitorFilter = searchParams.get('competitor');

  const fetchReports = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/reports');
      let filtered = data;
      if (competitorFilter) {
        filtered = data.filter((r: any) => r.competitor_id === parseInt(competitorFilter));
      }
      setReports(filtered);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, [competitorFilter]);

  const filteredReports = reports?.filter(r => 
    (r as any).competitor?.company_name.toLowerCase().includes(search.toLowerCase()) ||
    r.report_type.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-black text-text-primary tracking-tight">Intelligence Reports</h2>
          <p className="text-text-secondary font-medium">Synthetic deep-dives generated by Gemini AI</p>
        </div>
        <div className="relative w-full md:w-80">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-text-muted" size={18} />
          <input 
            type="text" 
            placeholder="Search reports..." 
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-12 pr-4 py-3 bg-surface border border-border-custom rounded-xl text-sm focus:outline-none focus:border-accent/40 placeholder:text-text-muted"
          />
        </div>
      </div>

      {loading ? (
        <Card><SkeletonTable rows={8} /></Card>
      ) : filteredReports && filteredReports.length > 0 ? (
        <Card padding={false} className="overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-surface2/50 text-text-muted text-[10px] font-black uppercase tracking-widest border-b border-border-custom">
                  <th className="px-8 py-5">Competitor</th>
                  <th className="px-8 py-5">Type</th>
                  <th className="px-8 py-5">Generated Date</th>
                  <th className="px-8 py-5 text-right">Access</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border-custom">
                {filteredReports.map((report: any) => (
                  <tr key={report.id} className="hover:bg-surface2/30 transition-colors group">
                    <td className="px-8 py-6">
                      <div className="flex flex-col">
                        <span className="font-bold text-text-primary">{report.competitor?.company_name}</span>
                        <span className="text-xs text-text-muted">{report.competitor?.industry}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <Badge variant="info">{report.report_type}</Badge>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex items-center gap-2 text-text-secondary text-sm font-medium">
                        <Calendar size={14} className="text-text-muted" />
                        {new Date(report.created_at).toLocaleDateString()}
                      </div>
                    </td>
                    <td className="px-8 py-6 text-right">
                      <Link href={`/reports/${report.id}`}>
                        <Button variant="secondary" size="sm" className="font-bold text-[10px] tracking-widest uppercase py-2">
                          View Data <ChevronRight size={14} className="ml-1" />
                        </Button>
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      ) : (
        <EmptyState 
          icon={FileSearch}
          heading="No reports found"
          subheading="Try adjusting your search or contact support to request a specific analysis."
        />
      )}
    </div>
  );
}
