"use client";

export const dynamic = "force-dynamic";
import React, { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import MainLayout from '@/components/layout/MainLayout';
import api from '@/lib/api';
import { Report, StockDataPoint } from '@/types';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Badge from '@/components/ui/Badge';
import { SkeletonText, SkeletonStockChart } from '@/components/ui/Skeleton';
import { ArrowLeft, Download, Printer, BookOpen, ChevronDown } from 'lucide-react';
import StockChart from '@/components/charts/StockChart';
import SalesChart from '@/components/charts/SalesChart';

export default function ReportDetailPage() {
  const { id } = useParams();
  const router = useRouter();
  const [report, setReport] = useState<Report & { competitor: any } | null>(null);
  const [stockData, setStockData] = useState<StockDataPoint[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchReport = async () => {
    setLoading(true);
    try {
      const { data } = await api.get(`/reports/${id}`);
      setReport(data);

      if (data.competitor?.stock_ticker) {
        try {
          const stockRes = await api.get(`/competitors/${data.competitor_id}/stock-data`);
          setStockData(stockRes.data);
        } catch (e) {
          console.error("No stock data available");
        }
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
  }, [id]);

  if (loading) return (
    <MainLayout title="Loading Report...">
      <div className="space-y-6">
        <SkeletonText lines={4} />
        <SkeletonStockChart />
        <SkeletonText lines={10} />
      </div>
    </MainLayout>
  );

  if (!report) return null;

  // Simple section parser
  const sections = report.content.split(/\d\.\s/).filter(Boolean);
  const sectionHeaders = [
    "Executive Summary",
    "Sales Analysis",
    "News & Key Events",
    "Stock Movement",
    "SEO Performance",
    "Keyword Recommendations",
    "Company Intelligence",
    "Threats & Opportunities",
    "Recommendations"
  ];

  return (
    <MainLayout title="Report Details">
      <div className="space-y-8 print:p-0">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 print:hidden">
          <Button variant="ghost" onClick={() => router.back()} className="font-bold text-xs uppercase tracking-wider">
            <ArrowLeft className="mr-2" size={16} /> Back to Reports
          </Button>
          <div className="flex gap-3">
            <Button variant="secondary" onClick={() => window.print()}>
              <Printer size={16} className="mr-2" /> Print
            </Button>
            <Button>
              <Download size={16} className="mr-2" /> Download PDF
            </Button>
          </div>
        </div>

        <div className="bg-surface2 rounded-3xl p-8 border border-border-custom relative overflow-hidden">
          <div className="absolute top-0 right-0 p-12 opacity-5 pointer-events-none">
            <BookOpen size={200} />
          </div>
          <div className="flex flex-col md:flex-row justify-between items-start gap-6 relative z-10">
            <div>
              <div className="flex items-center gap-3 mb-4">
                <Badge variant="info">{report.report_type}</Badge>
                <span className="text-text-muted text-sm font-bold tracking-widest uppercase">
                  {new Date(report.created_at).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
                </span>
              </div>
              <h2 className="text-4xl md:text-5xl font-black text-text-primary tracking-tight mb-2">
                {report.competitor.company_name}
              </h2>
              <p className="text-lg text-text-secondary font-medium">Strategic Competitive Intelligence Deep-Dive</p>
            </div>
            <div className="flex flex-col text-right">
              <span className="text-[10px] font-black text-text-muted tracking-[0.2em] uppercase mb-1">Generated by</span>
              <span className="text-xl font-black bg-gradient-primary bg-clip-text text-transparent">Jupid AI Gemini</span>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-4 gap-10">
          {/* TOC Sidebar */}
          <div className="hidden lg:block space-y-2 sticky top-24 h-fit print:hidden border-r border-border-custom pr-6">
            <p className="text-[10px] font-black text-text-muted tracking-[0.2em] uppercase mb-6">Report Sections</p>
            {sectionHeaders.map((header, idx) => (
              <a 
                key={idx} 
                href={`#section-${idx}`}
                className="block py-2 text-sm font-bold text-text-secondary hover:text-accent transition-colors"
              >
                {idx + 1}. {header}
              </a>
            ))}
          </div>

          <div className="lg:col-span-3 space-y-12">
            {/* Stock Chart Section (Special) */}
            {stockData.length > 0 && (
              <div id="section-3" className="scroll-mt-24 space-y-6">
                <div className="flex items-center justify-between border-b border-border-custom pb-4">
                  <h3 className="text-2xl font-black tracking-tight">3. Stock Movement</h3>
                  <Badge variant="success">Market Live</Badge>
                </div>
                <StockChart ticker={report.competitor.stock_ticker} data={stockData} />
              </div>
            )}

            {/* General Sections */}
            {sections.map((content, idx) => {
              // Adjust index for display if stock chart was inserted
              const sectionHeader = sectionHeaders[idx] || "Analysis";
              return (
                <div key={idx} id={`section-${idx}`} className="scroll-mt-24 space-y-6">
                  <div className="border-b border-border-custom pb-4">
                    <h3 className="text-2xl font-black tracking-tight">{idx + 1}. {sectionHeader}</h3>
                  </div>
                  <div className="text-text-secondary text-base leading-[1.8] font-medium whitespace-pre-line bg-surface/30 p-8 rounded-2xl border border-border-custom/30">
                    {content.trim()}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </MainLayout>
  );
}
